<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
    <link rel="stylesheet" href="../resources/public/index.css">
</head>
<body>
<form>
    <label>Enter range of IP's with mask:</label>
    <input type="text" size="40" placeholder="Javalin">
    <label>Enter amount of threads:</label>
    <input type="text" size="40" placeholder="Javalin">
    <input type="submit" value="Submit">
</form>
</body>
</html>