<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
    <link rel="stylesheet" type="text/css" href="index.css">
</head>
<body>
<div class="form-container">
    <form method="post">
        <label>Enter range of IP's with mask:</label>
        <input type="text" size="40" placeholder="ip" name="ip">
        <label>Enter amount of threads:</label>
        <input type="text" size="40" placeholder="amount of threads" name="threads">
        <input type="submit" value="Submit">
    </form>
</div>
</body>
</html>